### ISSUE TITLE
[BUG]http2: panic serving 10.107.9.130:36746: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by weini1** [kubedl-io/kubedl#171]
你好：
安装yaml安装了kubedl，查看pod成功running，查看log报错：
E0824 20:25:33.101649       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.7/tools/cache/reflector.go:167: Failed to watch *v1alpha1.XDLJob: failed to list *v1alpha1.XDLJob: Get https://10.96.0.1:443/apis/training.kubedl.io/v1alpha1/xdljobs?limit=500&resourceVersion=0: stream error: stream ID 60931; INTERNAL_ERROR
查看apiserver日志：
E0824 16:05:17.101869       1 wrap.go:39] apiserver panic'd on GET /apis/training.kubedl.io/v1alpha1/marsjobs?limit=500&resourceVersion=0
I0824 16:05:17.101921       1 log.go:172] http2: panic serving 10.107.9.130:36746: runtime error: invalid memory address or nil pointer dereference
除了安装kubedl，还需要安装什么？

**Environment**:
- KubeDL version: 0.4.0
- Kubernetes version (use `kubectl version`):1.16.3
- OS (e.g: `cat /etc/os-release`):18.04.4 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`):Linux mnode 4.15.0-76-generic #86-Ubuntu
- Install tools:yaml 
- Others:

**Comment by SimonCqk** [comment]
@weini1 hi weini, is this a `minikube` cluster? and would you post more context about logs printed by `apiserver` ?

**Comment by weini1** [comment]
hello,
this is kubeadm cluster，this is pod and service
root@mnode:~/wn/kubedl-master/example/tf# kubectl get pod,svc -A
NAMESPACE       NAME                                          READY   STATUS    RESTARTS   AGE
kube-system     pod/calico-kube-controllers-55754f75c-jm2ph   1/1     Running   0          9m25s
kube-system     pod/calico-node-294pq                         1/1     Running   0          8m25s
kube-system     pod/calico-node-8vz8b                         1/1     Running   0          8m35s
kube-system     pod/calico-node-k6fkb                         1/1     Running   0          9m25s
kube-system     pod/coredns-5644d7b6d9-mlst4                  1/1     Running   0          10m
kube-system     pod/coredns-5644d7b6d9-qjxqq                  1/1     Running   0          10m
kube-system     pod/etcd-mnode                                1/1     Running   0          10m
kube-system     pod/kube-apiserver-mnode                      1/1     Running   0          9m52s
kube-system     pod/kube-controller-manager-mnode             1/1     Running   0          9m59s
kube-system     pod/kube-proxy-6lv67                          1/1     Running   0          10m
kube-system     pod/kube-proxy-sgndd                          1/1     Running   0          8m35s
kube-system     pod/kube-proxy-trm7p                          1/1     Running   0          8m25s
kube-system     pod/kube-scheduler-mnode                      1/1     Running   0          11m
kubedl-system   pod/kubedl-7f4c55dfc9-gb5dz                   1/1     Running   0          6m7s

NAMESPACE     NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  11m
kube-system   service/kube-dns     ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   11m

Submit the TensorFlow job:
root@mnode:~/wn/kubedl-master/example/tf# kubectl apply -f tf_job_mnist.yaml 
error: error when retrieving current configuration of:
Resource: "training.kubedl.io/v1alpha1, Resource=tfjobs", GroupVersionKind: "training.kubedl.io/v1alpha1, Kind=TFJob"
Name: "mnist", Namespace: "kubedl-system"
Object: &{map["apiVersion":"training.kubedl.io/v1alpha1" "kind":"TFJob" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "name":"mnist" "namespace":"kubedl-system"] "spec":map["cleanPodPolicy":"None" "tfReplicaSpecs":map["Worker":map["replicas":'\x01' "restartPolicy":"Never" "template":map["spec":map["containers":[map["command":["python" "/var/tf_mnist/mnist_with_summaries.py" "--log_dir=/train/logs" "--learning_rate=0.01" "--batch_size=150"] "image":"kubedl/tf-mnist-with-summaries:1.0" "name":"tensorflow" "resources":map["limits":map["cpu":"2048m" "memory":"2Gi"] "requests":map["cpu":"1024m" "memory":"1Gi"]] "volumeMounts":[map["mountPath":"/train" "name":"training"]]]] "volumes":[map["hostPath":map["path":"/tmp/data" "type":"DirectoryOrCreate"] "name":"training"]]]]]]]]}
from server for: "tf_job_mnist.yaml": Get https://10.107.9.130:6443/apis/training.kubedl.io/v1alpha1/namespaces/kubedl-system/tfjobs/mnist: stream error: stream ID 81; INTERNAL_ERROR

apiserver logs:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x7b05840, 0xc01156c028, 0xc012e5bf00)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc00b815c80, 0xc01156c028, 0xc012e5bf00, 0xc019f98440)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2125 +0x89
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1859 +0x4f4
E0825 13:50:14.182517       1 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
goroutine 28928 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc0084c6180)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:107 +0x107
panic(0x3ce9340, 0xaa87850)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Structural).Unfold.func1(0xc014e51950, 0x0)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/unfold.go:38 +0xa2
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc014e99770, 0xc014e51950, 0xc014e99300)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:41 +0x48e
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc014e99770, 0xc014e51830, 0xc014e99400)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:48 +0x173
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc014e99770, 0xc014e517a0, 0xc014e99658)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:48 +0x173
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc014e99770, 0xc01293a7e0, 0xc01293a7e0)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:48 +0x173
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).Visit(...)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:35
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Structural).Unfold(0xc01293a7e0, 0xc01293a7e0)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/unfold.go:60 +0x58
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder.BuildSwagger(0xc01046a000, 0xc007c482d8, 0x8, 0x1010100, 0x0, 0xc010331560, 0xd0)
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.buildOpenAPIModelsForApply(0xc000aa2200, 0xc01046a000, 0xc007c482d8, 0x8, 0xc010014498, 0x0)
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).getOrCreateServingInfoFor(0xc000afc580, 0xc008498ff0, 0x24, 0xc00191b5a0, 0x1b, 0x0, 0x0, 0x0)
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).ServeHTTP(0xc000afc580, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc007c1ed00, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x38d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc0008f9f10, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x85
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x44ef910, 0x17, 0xc0007b5a70, 0xc0008f9f10, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x6c3
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc00a2fa2c0, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:254 +0x1f7
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc000390230, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x85
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x44ce2b4, 0xe, 0xc00034aab0, 0xc000390230, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x6c3
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc011506700, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:118 +0x162
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc00f9f2140, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x38d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc005e34310, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x85
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x44d1480, 0xf, 0xc006bbb5f0, 0xc005e34310, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x6c3
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x4fa
net/http.HandlerFunc.ServeHTTP(0xc006bf3240, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x5c7
net/http.HandlerFunc.ServeHTTP(0xc006c16b10, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x1f6f
net/http.HandlerFunc.ServeHTTP(0xc006bf3280, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba35000)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f8886ba8658, 0xc006bc40a8, 0xc00ba34f00)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:110 +0x696
net/http.HandlerFunc.ServeHTTP(0xc006bed310, 0x7f8886ba8658, 0xc006bc40a8, 0xc00ba34f00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc0084c6180, 0xc006c1c420, 0x7b1e900, 0xc006bc40a8, 0xc00ba34f00)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:112 +0xb3
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:98 +0x1b1

goroutine 28982 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3a33d00, 0xc011620d20)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc00fa97cd8, 0x1, 0x1)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3a33d00, 0xc011620d20)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc006c1c420, 0x7b11f00, 0xc00e478230, 0xc00ba34f00)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:118 +0x3ef
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x7b11f00, 0xc00e478230, 0xc00ba34e00)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xf3
net/http.HandlerFunc.ServeHTTP(0xc006c16b40, 0x7b11f00, 0xc00e478230, 0xc00ba34e00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x7b11f00, 0xc00e478230, 0xc00ba34c00)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x2b8
net/http.HandlerFunc.ServeHTTP(0xc006c16b70, 0x7b11f00, 0xc00e478230, 0xc00ba34c00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x7b11f00, 0xc00e478230, 0xc00ba34c00)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc006c1c440, 0x7b11f00, 0xc00e478230, 0xc00ba34c00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x7b05840, 0xc01156c020, 0xc012e5bd00)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x29c
net/http.HandlerFunc.ServeHTTP(0xc006c1c460, 0x7b05840, 0xc01156c020, 0xc012e5bd00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x7b05840, 0xc01156c020, 0xc012e5bd00)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x105
net/http.HandlerFunc.ServeHTTP(0xc006c1c480, 0x7b05840, 0xc01156c020, 0xc012e5bd00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc006c16ba0, 0x7b05840, 0xc01156c020, 0xc012e5bd00)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0041031e0, 0x7b05840, 0xc01156c020, 0xc012e5bd00)
        /usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.initNPNRequest.ServeHTTP(0xc00a7fb880, 0xc0041031e0, 0x7b05840, 0xc01156c020, 0xc012e5bd00)
        /usr/local/go/src/net/http/server.go:3323 +0x8d
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc00b815c80, 0xc01156c020, 0xc012e5bd00, 0xc019f98420)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2125 +0x89
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1859 +0x4f4
E0825 13:50:14.182534       1 wrap.go:39] apiserver panic'd on GET /apis/training.kubedl.io/v1alpha1/marsjobs?limit=500&resourceVersion=0
I0825 13:50:14.182579       1 log.go:172] http2: panic serving 10.107.9.130:41978: runtime error: invalid memory address or nil pointer dereference
goroutine 28928 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc0084c6180)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:107 +0x107
panic(0x3ce9340, 0xaa87850)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Structural).Unfold.func1(0xc014e51950, 0x0)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/unfold.go:38 +0xa2
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc014e99770, 0xc014e51950, 0xc014e99300)
        /workspace/anago-v1.16.1-beta.0.37+d647ddbd755faf/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:41 +0x48e

**Comment by SimonCqk** [comment]
it seems `apiserver` in your kubernetes cluster has broken :(
any other CRD objects can be successfully applied?
